### ISSUE TITLE
[INSTALL] bash: ember: command not found

### ISSUE THREAD

**Issue by inkredabull** [ryanflorence/ember-tools#18]
Unsure as to whether you want to address this as an issue; it was more of a sys config problem on my machine, but I thought I would share in case you want to guard for this out-of-the-box.

I did these two steps of the instructions:

`npm install -g ember-tools`
`mkdir my-app && cd my-app`

and then, after step three: 

`ember create js`

I got:

`-bash: ember: command not found`

System deets:

OSX 10.8.2
GNU bash, version 3.2.48(1)-release (x86_64-apple-darwin12)
node:  v0.8.16
npm: 1.1.69

I noticed that ember-tools was installed to:

/usr/local/share/npm/lib/node_modules/ember-tools

Opened a new tab (and hoping PATH would be set appropriately) - did not work.

Added /usr/local/share/npm/lib/node_modules/ember-tools/bin to my PATH.  Worked.

(I hate to post an issue without a Pull Request for the fix, but for the time being, I just want to kick-the-tires of the project before diving in to fixing anything yet.)

**Comment by quantumproducer** [comment]
I have this issue @ryanflorence , I tried adding that to my bash profile (OSX)

**Comment by ysonggit** [comment]
@ryanflorence Thank you, adding `export PATH=node_modules/.bin:$PATH` to .bash_profile works for me
